// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Welcome$ReactTemplate = require("./Welcome.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Welcome$ReactTemplate.make(/* array */[])), "app");

/*  Not a pure module */
