// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Pinata$PinataSdk = require("pinata-sdk/lib/js/src/Pinata.bs.js");

(( 
    global.fetch = require('node-fetch')
));

var hash = "<your ipfs content hash>";

var apiKey = "<your api key>";

var privateApiKey = "<your private api key>";

var pinata = Pinata$PinataSdk.configure(apiKey, privateApiKey, undefined, /* () */0);

Pinata$PinataSdk.pinHashToIPFS(pinata, hash).then((function (result) {
        console.log(result.ipfsHash);
        return Promise.resolve(result);
      }));

exports.hash = hash;
exports.apiKey = apiKey;
exports.privateApiKey = privateApiKey;
exports.pinata = pinata;
/*  Not a pure module */
